apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: coursebotics-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: coursebotics
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default
