apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: coursebotics
  namespace: coursebotics

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - network-policy.yaml
  - monitoring.yaml

commonLabels:
  app: coursebotics
  project: coursebotics

images:
  - name: nilbhungaliya11/coursebotics
    newTag: latest